-- Create view proprietenonbatie based on Qgis Models

COMMENT ON MATERIALIZED VIEW #schema_cadastrapp.proprietenonbatie IS 'Propriétés non bâties';
COMMENT ON COLUMN #schema_cadastrapp.commune.id_local IS 'Identifiant du local';
COMMENT ON COLUMN #schema_cadastrapp.commune.jdatat IS 'Date de l''acte';
COMMENT ON COLUMN #schema_cadastrapp.commune.comptecommunal IS 'Compte communal';
COMMENT ON COLUMN #schema_cadastrapp.commune.cgocommune IS 'Code commune INSEE';
COMMENT ON COLUMN #schema_cadastrapp.commune.ccopre IS 'Préfixe section';
COMMENT ON COLUMN #schema_cadastrapp.commune.ccosec IS 'Section';
COMMENT ON COLUMN #schema_cadastrapp.commune.dnupla IS 'Num de plan';
COMMENT ON COLUMN #schema_cadastrapp.commune.parcelle IS 'Parcelle';
COMMENT ON COLUMN #schema_cadastrapp.commune.ccovoi IS 'Code voie MAJIC2';
COMMENT ON COLUMN #schema_cadastrapp.commune.voie IS 'Voie';
COMMENT ON COLUMN #schema_cadastrapp.commune.ccoriv IS 'Code voie Rivoli';
COMMENT ON COLUMN #schema_cadastrapp.commune.dnvoiri IS 'Num voirie';
COMMENT ON COLUMN #schema_cadastrapp.commune.dindic IS 'Indice de répétition voirie';
COMMENT ON COLUMN #schema_cadastrapp.commune.natvoi IS 'Nature voie';
COMMENT ON COLUMN #schema_cadastrapp.commune.cconvo IS 'Code nature voie';
COMMENT ON COLUMN #schema_cadastrapp.commune.dvoilib IS 'Libellé voie';
COMMENT ON COLUMN #schema_cadastrapp.commune.dparpi IS 'Num parcelle primitive';
COMMENT ON COLUMN #schema_cadastrapp.commune.gparnf IS 'Indic parcelle non au plan';
COMMENT ON COLUMN #schema_cadastrapp.commune.ccostn IS 'Série tarif';
COMMENT ON COLUMN #schema_cadastrapp.commune.ccosub IS 'Indicatif de suf';
COMMENT ON COLUMN #schema_cadastrapp.commune.cgrnum IS 'Grp de nature de culture';
COMMENT ON COLUMN #schema_cadastrapp.commune.dsgrpf IS 'Ss-groupe alphabétique';
COMMENT ON COLUMN #schema_cadastrapp.commune.dclssf IS 'Classe dans le groupe';
COMMENT ON COLUMN #schema_cadastrapp.commune.cnatsp IS 'Code nature de culture spéciale';
COMMENT ON COLUMN #schema_cadastrapp.commune.dcntsf IS 'Contenance suf';
COMMENT ON COLUMN #schema_cadastrapp.commune.drcsuba IS 'Revenu cadastral revalorisé';
COMMENT ON COLUMN #schema_cadastrapp.commune.pdl IS 'Propriété divisée en lot';
COMMENT ON COLUMN #schema_cadastrapp.commune.dnulot IS 'Numéro de lot';
COMMENT ON COLUMN #schema_cadastrapp.commune.dreflf IS 'Réf livre foncier';
COMMENT ON COLUMN #schema_cadastrapp.commune.majposa IS 'Maj terrain constructible';
COMMENT ON COLUMN #schema_cadastrapp.commune.bisufad_com IS 'Base imposition suf com';
COMMENT ON COLUMN #schema_cadastrapp.commune.bisufad_dep IS 'Base imposition suf dep';
COMMENT ON COLUMN #schema_cadastrapp.commune.bisufad_gp IS 'base imposition suf groupe com';